apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-rw-ops
  namespace: ops
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: ops
roleRef:
  kind: Role
  name: operator-readwrite
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-ro-apps
  namespace: apps
subjects:
  - kind: ServiceAccount
    name: operator
    namespace: ops
roleRef:
  kind: Role
  name: operator-readonly
  apiGroup: rbac.authorization.k8s.io
