apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-apps-guardrails
  namespace: apps
spec:
  hard:
    pods: "20"
    requests.cpu: "600m"
    requests.memory: "600Mi"
    limits.cpu: "1200m"
    limits.memory: "900Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-apps-defaults
  namespace: apps
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "25m"
      memory: "64Mi"
    default:
      cpu: "200m"
      memory: "256Mi"
    max:
      cpu: "500m"
      memory: "512Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-platform-guardrails
  namespace: platform
spec:
  hard:
    pods: "20"
    requests.cpu: "300m"
    requests.memory: "300Mi"
    limits.cpu: "700m"
    limits.memory: "500Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-platform-defaults
  namespace: platform
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "25m"
      memory: "64Mi"
    default:
      cpu: "150m"
      memory: "192Mi"
    max:
      cpu: "400m"
      memory: "384Mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-ops-guardrails
  namespace: ops
spec:
  hard:
    pods: "15"
    requests.cpu: "300m"
    requests.memory: "300Mi"
    limits.cpu: "700m"
    limits.memory: "500Mi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr-ops-defaults
  namespace: ops
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: "25m"
      memory: "64Mi"
    default:
      cpu: "150m"
      memory: "192Mi"
    max:
      cpu: "400m"
      memory: "384Mi"
